module.exports = {
  docs: [
    "welcome",
    {
      type: "category",
      label: "0 - Getting started",
      items: [
        {
          type: "autogenerated",
          dirName: "getting-started",
        },
      ],
    },
    "ingest",
    {
      type: "category",
      label: "2 - Transforming data",
      items: [
        {
          type: "autogenerated",
          dirName: "transform",
        },
      ],
    },
    "deliver",
    "faq",
    {
      type: "category",
      label: "Key concepts",
      items: [
        {
          type: "autogenerated",
          dirName: "key-concepts",
        },
      ],
    },
  ],
  integrations: [{ type: "autogenerated", dirName: "integrations" }],
  tutorials: [{ type: "autogenerated", dirName: "tutorials" }],
  reference: [{ type: "autogenerated", dirName: "reference" }],
};
