module.exports = {
  docs: [
    'welcome',
    'getting-started',
    'ingest',
    {
      type: 'category',
      label: '2 - Transforming data',
      items: [
       {
        type: 'autogenerated',
        dirName: 'transform'
       }
      ],
    },
    'deliver',
  ],
  integrations: [{ type: "autogenerated", dirName: "integrations" }],
  tutorials: [{ type: "autogenerated", dirName: "tutorials" }],
  reference: [{ type: "autogenerated", dirName: "reference" }],
};
