name: CI

on:
  workflow_dispatch:
    branches:
      - '*'
  push:
    branches: [ master ]

jobs:
  scrape-site:
    name: Scrape latest deployed site version
    runs-on: ubuntu-latest

    env:
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      API_KEY: ${{ secrets.API_KEY }}
      NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Wait for Netlify Deploy
        uses: probablyup/wait-for-netlify-action@3.2.0
        id: waitForDeployment
        with:
          site_id: '0b6465f0-2e60-4bf2-ba9a-b761fb374e91'
          max_timeout: 90

      - name: Run Docker container
        run: |
          docker run -e APPLICATION_ID -e API_KEY  -e CONFIG="$(cat ./algolia/config.json)" algolia/docsearch-scraper